name: deploy

on:
  push:
    branches:
      - "main"
jobs:
  build:
    run-on: ubuntu-latest
    steps:
    -
      name: Checkout
      uses: actions/checkout@v4
    -
      name: login to  Docker hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    -
      name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    -
      nanme: Build and push
      uses: docker/build-push-action@v5
      with:
        context:
        files: ./Dockerfile
        push: true
        tags: ${{ secrets.DOCKERHUB_USERNAME }} /nest-demo:latests
        
        
